### PR TITLE
feat: add regtest support

### PR DESCRIPTION
**Pull request by louneskmt**
Quick PR to add Regtest as a network option. Tested and working so far.

### CODE REVIEW

**Review by 0xB10C — APPROVED** [review]
Thanks!

**Comment by louneskmt** [comment]
FYI, I now maintain a `nightly` Docker image of `fork-observer`: [source](https://github.com/ln-markets/images/tree/master/docker/fork-observer) (with example), [Docker Hub](https://hub.docker.com/r/lnmarkets/fork-observer/tags), [GHCR](https://github.com/ln-markets/images/pkgs/container/fork-observer). Built for both `linux/amd64` and `linux/arm64` twice a day.

**Comment by 0xB10C** [comment]
Cool! There's also https://hub.docker.com/r/b10c/fork-observer.

I'm interested in hearing what you are using fork-observer for. Also, feel free to send me any feedback or questions you might have. Happy to help!

**Comment by louneskmt** [comment]
Nice, I didn't see it so I quickly added it to our repo. Btw, I had to remove the rust target from your Dockerfile to make it work on my computer (before using our regular Dockerfile for Rust projects, with cache etc).

So far just playing around, I thought it could be useful to run this in our dev stack to better visualize my tests of rolling back the chain (tracking the confirmation/irreversibility states of watched bitcoin transactions, for deposits, etc).

Thank you for this cool project!

**Pull request merged**
