### PR TITLE
show header difficulty and highlight difficulty 1 blocks

### LINKED ISSUE #48: Mark difficulty 1 (testnet) blocks
To increase the pleasure of re-orging them.

### PR DESCRIPTION
**Pull request by 0xB10C**
closes #48 

currently running this on https://fork.observer/?network=4

image

### CODE REVIEW

**Comment by 0xB10C** [comment]
cc @Sjors

**Comment by Sjors** [comment]
Nice, makes it much easier to spot these cowardly blocks :-)

cc @gitgab19

**Comment by fjahr** [comment]
Awesome :)

**Comment by 0xB10C** [comment]
Could add some docs and maybe a toggle for this, but will do some other time.

**Pull request merged**
